apiVersion: v1
kind: Secret
metadata:
  name: kafka-credentials
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "customer-service.labels" . | nindent 4 }}
type: Opaque
stringData:
  kafka-user: {{ .Values.secrets.kafkaUser | quote }}
  kafka-password: {{ .Values.secrets.kafkaPassword | quote }}
