apiVersion: v1
kind: Secret
metadata:
  name: customer-service-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "customer-service.labels" . | nindent 4 }}
type: Opaque
stringData:
  DB_USER: {{ .Values.secrets.dbUser | quote }}
  DB_PASSWORD: {{ .Values.secrets.dbPassword | quote }}
  KAFKA_USER: {{ .Values.secrets.kafkaUser | quote }}
  KAFKA_PASSWORD: {{ .Values.secrets.kafkaPassword | quote }}
