apiVersion: v1
kind: Service
metadata:
  name: customer-service
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "customer-service.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "customer-service.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: http
